
name: ziti-mattermost-action-py
on:
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
  pull_request:
    types: [opened, reopened]
  push:
  fork:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  ziti-webhook:
    runs-on: ubuntu-latest
    name: Ziti Mattermost Action - Py
    steps:
      - uses: dovholuknf/mm-notification-action@main
        with:
          identityFile: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          githubEvent:  ${{ toJson(github.event) }}
          url: ${{ secrets.ZHOOK_URL }}