name: mattermost-ziti-webhook
on:
  create:
  delete:
  issues:
  issue_comment:
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
  pull_request:
    types: [opened, reopened]
  push:
  fork:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  mattermost-ziti-webhook:
    runs-on: ubuntu-latest
    name: POST Webhook
    if: github.repository_owner == 'openziti-test-kitchen' && github.actor != 'dependabot[bot]'
    env:
      ZITI_LOG: 99
      ZITI_NODEJS_LOG: 99
    steps:
      - uses: openziti/ziti-webhook-action@main
        with:
          ziti-id: ${{ secrets.ZITI_MATTERMOST_IDENTITY }}
          webhook-url: ${{ secrets.ZITI_MATTERMOST_WEBHOOK_URL }}
          webhook-secret: ${{ secrets.ZITI_MATTERMOSTI_WEBHOOK_SECRET }}